"""Recipe export tests - Sprint 4 T1-A5.

Covers the format-agnostic context builder, every one of the five
renderers, the "no recommendation" gap path, and round-trip
parsing where applicable (JSON / shell-script smoke).
"""

from __future__ import annotations

import json
import re
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(ROOT / "apps" / "api"))

from planmyagents_api.planner.recipe_export import (  # noqa: E402
    RECIPE_FORMATS,
    RecipeContext,
    RecipeStep,
    RecommendedProvider,
    build_recipe_context,
    render_recipe,
)

# ---------------------------------------------------------------------------
# Fixtures.
# ---------------------------------------------------------------------------


def _mcp_rec(provider_id: str, **overrides) -> RecommendedProvider:
    defaults = {
        "provider_id": provider_id,
        "display_name": provider_id.replace("-", " ").title(),
        "provider_type": "mcp_server",
        "docs_url": f"https://docs.example.com/{provider_id}",
        "install_command": f"npx -y @example/{provider_id}",
        "api_base_url": "",
        "required_env_vars": ("EXAMPLE_API_KEY",),
        "verification_status": "known_provider",
        "benchmark_status": "passed",
    }
    defaults.update(overrides)
    return RecommendedProvider(**defaults)


def _api_rec(provider_id: str, **overrides) -> RecommendedProvider:
    defaults = {
        "provider_id": provider_id,
        "display_name": provider_id.replace("-", " ").title(),
        "provider_type": "api_provider",
        "docs_url": f"https://docs.example.com/{provider_id}",
        "install_command": "",
        "api_base_url": "https://api.example.com",
        "required_env_vars": ("EXAMPLE_BEARER_TOKEN",),
        "verification_status": "registered_in_directory",
        "benchmark_status": "not_started",
    }
    defaults.update(overrides)
    return RecommendedProvider(**defaults)


def _two_step_context(*, with_gap: bool = False) -> RecipeContext:
    step2_rec = None if with_gap else _api_rec("acme-api")
    return RecipeContext(
        goal_id="g_test_1234",
        goal_text="Verify an email and then enrich the contact.",
        steps=(
            RecipeStep(
                ordinal=1,
                capability="email_verification",
                description="Verify a single email address.",
                inputs={"email": "deepraj@example.com"},
                recommendation=_mcp_rec("hunter-mcp"),
            ),
            RecipeStep(
                ordinal=2,
                capability="contact_enrichment",
                description="Enrich the contact with company data.",
                inputs={},
                recommendation=step2_rec,
            ),
        ),
        planner_tier="groq:llama-4-scout",
        cost_estimate_usd=0.0123,
        notes=("Recipe generated by PlanMyAgents.",),
    )


def _unsupported_will_fail_context() -> RecipeContext:
    plan_payload = {
        "status": "unsupported",
        "sub_tasks": [
            {"capability": "general_research", "description": "Research gifts."},
            {"capability": "shopping_search", "description": "Find sellers."},
        ],
        "discovery": {
            "agentic_results": [
                {
                    "provider_id": "ai-conveo-conveo",
                    "display_name": "Conveo",
                    "provider_type": "mcp_server",
                    "install_command": "npx -y @conveo/mcp",
                    "capabilities": [{"id": "general_research"}],
                    "route_status": "will_fail",
                    "will_fail": True,
                    "will_fail_reasons": ["Not relevant or routable for this goal."],
                },
                {
                    "provider_id": "imaginary-shop-api",
                    "display_name": "Imaginary Shop API",
                    "provider_type": "api_provider",
                    "api_base_url": "https://api.example.test",
                    "capabilities": [{"id": "shopping_search"}],
                    "route_status": "will_fail",
                    "will_fail": True,
                    "will_fail_reasons": ["No executable adapter exists."],
                },
            ]
        },
    }
    return build_recipe_context(
        goal_id="g_refused",
        goal_text="find the best gift for a 3 year old",
        plan_payload=plan_payload,
    )


# ---------------------------------------------------------------------------
# Context builder.
# ---------------------------------------------------------------------------


class BuildRecipeContextTest(unittest.TestCase):
    def test_handles_empty_plan_payload(self) -> None:
        ctx = build_recipe_context(
            goal_id="g_empty", goal_text="(empty)", plan_payload={}
        )
        self.assertEqual(ctx.steps, ())
        self.assertEqual(ctx.step_count, 0)
        self.assertEqual(ctx.covered_step_count, 0)
        self.assertEqual(
            ctx.coverage.to_dict(),
            {
                "step_count": 0,
                "recommended_step_count": 0,
                "exportable_step_count": 0,
                "gap_count": 0,
                "status": "empty",
            },
        )
        self.assertEqual(ctx.planner_tier, "")

    def test_matches_sub_tasks_to_discovery_candidates(self) -> None:
        plan_payload = {
            "status": "executable",
            "sub_tasks": [
                {
                    "capability": "email_verification",
                    "description": "Verify an email.",
                    "inputs": {"email": "x@y.com"},
                }
            ],
            "discovery": {
                "agentic_results": [
                    {
                        "id": "hunter-mcp",
                        "display_name": "Hunter MCP",
                        "provider_type": "mcp_server",
                        "docs_url": "https://hunter.io",
                        "install_command": "npx -y @hunter/mcp",
                        "required_env_vars": ["HUNTER_API_KEY"],
                        "verification_status": "known_provider",
                        "benchmark_status": "passed",
                        "capabilities": [{"id": "email_verification"}],
                    }
                ]
            },
            "planner": {
                "llm_quality": {"planner": {"tier_used": "groq:llama-4-scout"}}
            },
            "cost_estimate": {"total_usd": 0.005},
        }
        ctx = build_recipe_context(
            goal_id="g_xyz", goal_text="Verify x@y.com", plan_payload=plan_payload
        )
        self.assertEqual(ctx.step_count, 1)
        self.assertEqual(ctx.covered_step_count, 1)
        self.assertEqual(ctx.coverage.status, "complete")
        self.assertEqual(ctx.coverage.recommended_step_count, 1)
        self.assertEqual(ctx.coverage.exportable_step_count, 1)
        self.assertEqual(ctx.coverage.gap_count, 0)
        step = ctx.steps[0]
        self.assertEqual(step.recommendation.provider_id, "hunter-mcp")
        self.assertEqual(step.recommendation.required_env_vars, ("HUNTER_API_KEY",))
        self.assertEqual(ctx.planner_tier, "groq:llama-4-scout")
        self.assertAlmostEqual(ctx.cost_estimate_usd, 0.005)

    def test_emits_gap_note_when_some_steps_have_no_recommendation(self) -> None:
        plan_payload = {
            "sub_tasks": [
                {"capability": "email_verification", "description": "Verify."},
                {"capability": "rocket_launching", "description": "Launch rocket."},
            ],
            "discovery": {
                "agentic_results": [
                    {
                        "id": "hunter-mcp",
                        "display_name": "Hunter MCP",
                        "provider_type": "mcp_server",
                        "install_command": "npx -y @hunter/mcp",
                        "capabilities": [{"id": "email_verification"}],
                    }
                ]
            },
        }
        ctx = build_recipe_context(
            goal_id="g", goal_text="t", plan_payload=plan_payload
        )
        self.assertEqual(ctx.covered_step_count, 1)
        self.assertEqual(ctx.coverage.status, "partial")
        self.assertEqual(ctx.coverage.recommended_step_count, 1)
        self.assertEqual(ctx.coverage.exportable_step_count, 1)
        self.assertEqual(ctx.coverage.gap_count, 1)
        self.assertEqual(ctx.steps[1].recommendation, None)
        self.assertTrue(any("TODO" in n or "no recommended" in n for n in ctx.notes))

    def test_will_fail_candidates_do_not_become_recommendations(self) -> None:
        plan_payload = {
            "status": "unsupported",
            "sub_tasks": [
                {
                    "capability": "general_research",
                    "description": "Research gift ideas.",
                }
            ],
            "discovery": {
                "agentic_results": [
                    {
                        "provider_id": "ai-conveo-conveo",
                        "display_name": "Conveo",
                        "provider_type": "mcp_server",
                        "capabilities": [{"id": "general_research"}],
                        "verification_status": "registered_in_directory",
                        "route_status": "will_fail",
                        "will_fail": True,
                        "will_fail_reasons": [
                            "Executable adapter or protocol client is not implemented yet."
                        ],
                    }
                ]
            },
        }

        ctx = build_recipe_context(
            goal_id="g_gift",
            goal_text="find a gift for a 3 year old",
            plan_payload=plan_payload,
        )

        self.assertEqual(ctx.covered_step_count, 0)
        self.assertEqual(ctx.coverage.status, "gap_only")
        self.assertEqual(ctx.coverage.gap_count, 1)
        self.assertEqual(ctx.coverage.exportable_step_count, 0)
        self.assertIsNone(ctx.steps[0].recommendation)
        self.assertTrue(any("refused" in note for note in ctx.notes))
        self.assertTrue(any("TODO" in note or "no recommended" in note for note in ctx.notes))

    def test_emits_refusal_note_when_plan_is_unsupported(self) -> None:
        plan_payload = {
            "status": "unsupported",
            "sub_tasks": [
                {"capability": "rocket_launching", "description": "Launch rocket."}
            ],
        }
        ctx = build_recipe_context(
            goal_id="g", goal_text="t", plan_payload=plan_payload
        )
        self.assertTrue(any("refused" in n for n in ctx.notes))


# ---------------------------------------------------------------------------
# Format dispatcher.
# ---------------------------------------------------------------------------


class RenderRecipeDispatcherTest(unittest.TestCase):
    def test_every_advertised_format_renders(self) -> None:
        ctx = _two_step_context()
        for fmt in RECIPE_FORMATS:
            with self.subTest(format=fmt):
                out = render_recipe(ctx, fmt)
                self.assertTrue(out.body, f"{fmt} produced empty body")
                self.assertTrue(out.content_type, f"{fmt} missing content_type")
                self.assertTrue(
                    out.filename_suffix.startswith("."),
                    f"{fmt} filename suffix not dot-prefixed",
                )

    def test_unknown_format_raises(self) -> None:
        with self.assertRaises(ValueError):
            render_recipe(_two_step_context(), "totally_not_a_format")


# ---------------------------------------------------------------------------
# Markdown renderer.
# ---------------------------------------------------------------------------


class MarkdownRendererTest(unittest.TestCase):
    def test_includes_goal_text_step_count_and_recommendation(self) -> None:
        out = render_recipe(_two_step_context(), "markdown")
        text = out.body.decode("utf-8")
        self.assertIn("# Recipe for: Verify an email and then enrich the contact.", text)
        self.assertIn("Step 1 — email_verification", text)
        self.assertIn("Hunter Mcp", text)
        self.assertIn("npx -y @example/hunter-mcp", text)
        self.assertIn("EXAMPLE_API_KEY", text)
        # cost estimate surfaces in the header
        self.assertIn("Estimated cost: $0.0123 USD", text)

    def test_gap_step_renders_todo_block(self) -> None:
        out = render_recipe(_two_step_context(with_gap=True), "markdown")
        text = out.body.decode("utf-8")
        self.assertIn("No recommended provider yet", text)
        self.assertIn("contact_enrichment", text)

    def test_refused_plan_markdown_is_gap_runbook(self) -> None:
        out = render_recipe(_unsupported_will_fail_context(), "markdown")
        text = out.body.decode("utf-8")
        self.assertIn("status `gap_only`", text)
        self.assertIn("0 recommended, 0 exportable, 2 gaps", text)
        self.assertIn("No recommended provider yet", text)
        self.assertNotIn("covered by a recommendation", text)


# ---------------------------------------------------------------------------
# Claude Desktop JSON renderer.
# ---------------------------------------------------------------------------


class ClaudeDesktopJsonRendererTest(unittest.TestCase):
    def test_output_is_valid_json_with_mcpservers_key(self) -> None:
        out = render_recipe(_two_step_context(), "claude_desktop_json")
        payload = json.loads(out.body.decode("utf-8"))
        self.assertIn("mcpServers", payload)
        self.assertIn("hunter-mcp", payload["mcpServers"])
        entry = payload["mcpServers"]["hunter-mcp"]
        self.assertEqual(entry["command"], "npx")
        self.assertEqual(entry["args"], ["-y", "@example/hunter-mcp"])
        self.assertEqual(entry["env"], {"EXAMPLE_API_KEY": "YOUR_EXAMPLE_API_KEY_HERE"})

    def test_non_mcp_step_is_surfaced_in_planmyagents_block(self) -> None:
        out = render_recipe(_two_step_context(), "claude_desktop_json")
        payload = json.loads(out.body.decode("utf-8"))
        non_mcp = payload["_planmyagents"]["non_mcp_steps"]
        self.assertEqual(len(non_mcp), 1)
        self.assertEqual(non_mcp[0]["provider_id"], "acme-api")
        self.assertEqual(non_mcp[0]["provider_type"], "api_provider")

    def test_gap_step_is_surfaced_in_missing_block(self) -> None:
        out = render_recipe(_two_step_context(with_gap=True), "claude_desktop_json")
        payload = json.loads(out.body.decode("utf-8"))
        missing = payload["_planmyagents"]["missing_steps"]
        self.assertEqual(len(missing), 1)
        self.assertEqual(missing[0]["capability"], "contact_enrichment")

    def test_mcp_without_install_command_is_not_added_to_mcpservers(self) -> None:
        ctx = RecipeContext(
            goal_id="g_no_install",
            goal_text="Use an MCP server with missing install docs.",
            steps=(
                RecipeStep(
                    ordinal=1,
                    capability="email_verification",
                    description="Verify email.",
                    recommendation=_mcp_rec("unknown-mcp", install_command=""),
                ),
            ),
        )
        out = render_recipe(ctx, "claude_desktop_json")
        payload = json.loads(out.body.decode("utf-8"))
        self.assertEqual(payload["mcpServers"], {})
        self.assertEqual(
            payload["_planmyagents"]["unexportable_steps"][0]["reason"],
            "MCP install command is unknown.",
        )

    def test_refused_plan_has_no_mcp_server_entries(self) -> None:
        out = render_recipe(_unsupported_will_fail_context(), "claude_desktop_json")
        payload = json.loads(out.body.decode("utf-8"))
        self.assertEqual(payload["mcpServers"], {})
        self.assertEqual(len(payload["_planmyagents"]["missing_steps"]), 2)


# ---------------------------------------------------------------------------
# Cursor renderer.
# ---------------------------------------------------------------------------


class CursorPromptRendererTest(unittest.TestCase):
    def test_output_is_valid_json_with_mcpservers_key(self) -> None:
        out = render_recipe(_two_step_context(), "cursor_prompt")
        payload = json.loads(out.body.decode("utf-8"))
        self.assertIn("mcpServers", payload)
        self.assertIn("hunter-mcp", payload["mcpServers"])

    def test_includes_system_prompt_template_with_step_lines(self) -> None:
        out = render_recipe(_two_step_context(), "cursor_prompt")
        payload = json.loads(out.body.decode("utf-8"))
        prompt = payload["_planmyagents"]["system_prompt_template"]
        self.assertIn("Step 1 (email_verification)", prompt)
        self.assertIn("Hunter Mcp", prompt)
        self.assertIn("Step 2 (contact_enrichment)", prompt)

    def test_coverage_block_lists_status_per_step(self) -> None:
        out = render_recipe(_two_step_context(with_gap=True), "cursor_prompt")
        payload = json.loads(out.body.decode("utf-8"))
        coverage = payload["_planmyagents"]["coverage"]
        self.assertEqual(coverage[0]["status"], "recommended")
        self.assertEqual(coverage[1]["status"], "missing")

    def test_refused_plan_cursor_config_has_no_mcp_servers(self) -> None:
        out = render_recipe(_unsupported_will_fail_context(), "cursor_prompt")
        payload = json.loads(out.body.decode("utf-8"))
        self.assertEqual(payload["mcpServers"], {})
        self.assertTrue(
            all(item["status"] == "missing" for item in payload["_planmyagents"]["coverage"])
        )


# ---------------------------------------------------------------------------
# n8n JSON renderer.
# ---------------------------------------------------------------------------


class N8nJsonRendererTest(unittest.TestCase):
    def test_output_is_valid_n8n_json(self) -> None:
        out = render_recipe(_two_step_context(), "n8n_json")
        self.assertEqual(out.content_type, "application/json")
        payload = json.loads(out.body.decode("utf-8"))
        self.assertIn("nodes", payload)
        self.assertIn("connections", payload)
        self.assertFalse(payload["active"])
        self.assertEqual(payload["_planmyagents"]["coverage"]["status"], "complete")
        self.assertEqual(len(payload["nodes"]), 2)
        self.assertEqual(payload["nodes"][0]["type"], "n8n-nodes-base.stickyNote")
        self.assertEqual(payload["nodes"][1]["type"], "n8n-nodes-base.httpRequest")

    def test_gap_step_emits_sticky_note_node(self) -> None:
        out = render_recipe(_two_step_context(with_gap=True), "n8n_json")
        payload = json.loads(out.body.decode("utf-8"))
        self.assertTrue(
            any(node["type"] == "n8n-nodes-base.stickyNote" for node in payload["nodes"])
        )

    def test_refused_plan_n8n_export_has_no_http_nodes(self) -> None:
        out = render_recipe(_unsupported_will_fail_context(), "n8n_json")
        payload = json.loads(out.body.decode("utf-8"))
        node_types = {node["type"] for node in payload["nodes"]}
        self.assertEqual(node_types, {"n8n-nodes-base.stickyNote"})
        self.assertEqual(payload["_planmyagents"]["coverage"]["status"], "gap_only")


# ---------------------------------------------------------------------------
# CLI renderer.
# ---------------------------------------------------------------------------


class CliRendererTest(unittest.TestCase):
    def test_output_is_executable_bash_script(self) -> None:
        out = render_recipe(_two_step_context(), "cli")
        text = out.body.decode("utf-8")
        self.assertTrue(text.startswith("#!/usr/bin/env bash"))
        self.assertIn("set -euo pipefail", text)
        # Required env-var preflight block
        self.assertIn("export EXAMPLE_API_KEY=", text)
        self.assertIn("export EXAMPLE_BEARER_TOKEN=", text)
        # MCP step launches via install command
        self.assertIn("npx -y @example/hunter-mcp", text)
        # API step issues a curl
        self.assertIn("curl -sS", text)
        # Step-gated prompt
        self.assertTrue(
            re.search(r"Press ENTER to run step 1", text),
            "missing step-1 confirmation prompt",
        )

    def test_gap_step_emits_todo_only(self) -> None:
        out = render_recipe(_two_step_context(with_gap=True), "cli")
        text = out.body.decode("utf-8")
        self.assertIn("TODO: no recommended provider", text)
        # Should NOT issue a curl for the gap step
        self.assertEqual(text.count("curl -sS"), 0)

    def test_refused_plan_cli_has_no_executable_provider_calls(self) -> None:
        out = render_recipe(_unsupported_will_fail_context(), "cli")
        text = out.body.decode("utf-8")
        self.assertIn("TODO: no recommended provider", text)
        self.assertNotIn("npx -y @conveo/mcp", text)
        self.assertNotIn("curl -sS", text)


# ---------------------------------------------------------------------------
# Phase-1 regression tests — B1..B6 from docs/manual-test-log.md
#
# Each test uses a real registry provider so we exercise the
# registry-lookup path. The fixture providers below mirror the shape
# the discovery payload emits so the (provider_id, capability) pair
# resolves in ``registry_lookup``.
# ---------------------------------------------------------------------------


def _registry_step(
    *,
    ordinal: int,
    provider_id: str,
    capability: str,
    provider_type: str,
    api_base_url: str,
    required_env_vars: tuple[str, ...],
    description: str = "step",
) -> RecipeStep:
    rec = RecommendedProvider(
        provider_id=provider_id,
        display_name=provider_id,
        provider_type=provider_type,
        docs_url="",
        install_command="",
        api_base_url=api_base_url,
        required_env_vars=required_env_vars,
        verification_status="known_provider",
        benchmark_status="passed",
    )
    return RecipeStep(
        ordinal=ordinal,
        capability=capability,
        description=description,
        recommendation=rec,
    )


def _registry_context(*steps: RecipeStep) -> RecipeContext:
    return RecipeContext(
        goal_id="g_registry",
        goal_text="Registry-backed test goal.",
        steps=steps,
    )


class PhaseOneRegressionTests(unittest.TestCase):
    """B1..B6 from docs/manual-test-log.md — registry-aware HTTP wiring."""

    # ---- B1: n8n URL uses registry path, not capability slug. -------------
    def test_b1_n8n_url_uses_registry_path_for_apollo(self) -> None:
        ctx = _registry_context(
            _registry_step(
                ordinal=1,
                provider_id="apollo",
                capability="contact_enrichment",
                provider_type="api_provider",
                api_base_url="https://api.apollo.io/v1",
                required_env_vars=("APOLLO_API_KEY",),
            ),
        )
        payload = json.loads(render_recipe(ctx, "n8n_json").body.decode("utf-8"))
        http_nodes = [n for n in payload["nodes"] if n["type"] == "n8n-nodes-base.httpRequest"]
        self.assertEqual(len(http_nodes), 1)
        url = http_nodes[0]["parameters"]["url"]
        self.assertEqual(url, "https://api.apollo.io/v1/v1/people/match")
        self.assertNotIn("contact-enrichment", url)

    # ---- B2: n8n method follows registry (POST), not hardcoded GET. -------
    def test_b2_n8n_method_follows_registry_for_apollo(self) -> None:
        ctx = _registry_context(
            _registry_step(
                ordinal=1,
                provider_id="apollo",
                capability="contact_enrichment",
                provider_type="api_provider",
                api_base_url="https://api.apollo.io/v1",
                required_env_vars=("APOLLO_API_KEY",),
            ),
        )
        payload = json.loads(render_recipe(ctx, "n8n_json").body.decode("utf-8"))
        http_node = next(
            n for n in payload["nodes"] if n["type"] == "n8n-nodes-base.httpRequest"
        )
        self.assertEqual(http_node["parameters"]["method"], "POST")

    # ---- B3: n8n header name comes from registry, not env-var heuristic. --
    def test_b3_n8n_header_name_uses_registry_for_apollo(self) -> None:
        ctx = _registry_context(
            _registry_step(
                ordinal=1,
                provider_id="apollo",
                capability="contact_enrichment",
                provider_type="api_provider",
                api_base_url="https://api.apollo.io/v1",
                required_env_vars=("APOLLO_API_KEY",),
            ),
        )
        payload = json.loads(render_recipe(ctx, "n8n_json").body.decode("utf-8"))
        http_node = next(
            n for n in payload["nodes"] if n["type"] == "n8n-nodes-base.httpRequest"
        )
        params = http_node["parameters"]["headerParameters"]["parameters"]
        self.assertEqual(len(params), 1)
        self.assertEqual(params[0]["name"], "X-Api-Key")
        self.assertEqual(params[0]["value"], "={{$env.APOLLO_API_KEY}}")
        self.assertNotIn("Bearer", params[0]["value"])

    # ---- B4: CLI does not prefix Bearer when scheme is header/basic. ------
    def test_b4_cli_no_bearer_prefix_for_apollo_header_auth(self) -> None:
        ctx = _registry_context(
            _registry_step(
                ordinal=1,
                provider_id="apollo",
                capability="contact_enrichment",
                provider_type="api_provider",
                api_base_url="https://api.apollo.io/v1",
                required_env_vars=("APOLLO_API_KEY",),
            ),
        )
        text = render_recipe(ctx, "cli").body.decode("utf-8")
        self.assertIn('-H "X-Api-Key: ${APOLLO_API_KEY}"', text)
        self.assertNotIn("Bearer ${APOLLO_API_KEY}", text)
        self.assertIn("-X POST", text)
        self.assertIn("https://api.apollo.io/v1/v1/people/match", text)

    def test_b4_cli_uses_basic_auth_for_razorpay(self) -> None:
        ctx = _registry_context(
            _registry_step(
                ordinal=1,
                provider_id="razorpay-payments",
                capability="payment_authorization",
                provider_type="payment_provider",
                api_base_url="https://api.razorpay.com/v1",
                required_env_vars=("RAZORPAY_KEY_ID", "RAZORPAY_KEY_SECRET"),
            ),
        )
        text = render_recipe(ctx, "cli").body.decode("utf-8")
        self.assertIn('-u "${RAZORPAY_KEY_ID}:${RAZORPAY_KEY_SECRET}"', text)
        self.assertNotIn("Bearer ${RAZORPAY_KEY_ID}", text)
        self.assertNotIn('Authorization:', text.replace("# Calling", ""))
        self.assertIn("-X POST", text)
        self.assertIn("https://api.razorpay.com/v1/v1/orders", text)

    def test_b4_cli_keeps_bearer_for_resend(self) -> None:
        ctx = _registry_context(
            _registry_step(
                ordinal=1,
                provider_id="resend-emails",
                capability="email_send",
                provider_type="api_provider",
                api_base_url="https://api.resend.com",
                required_env_vars=("RESEND_API_KEY",),
            ),
        )
        text = render_recipe(ctx, "cli").body.decode("utf-8")
        self.assertIn('-H "Authorization: Bearer ${RESEND_API_KEY}"', text)
        self.assertIn("-X POST", text)
        self.assertIn("https://api.resend.com/emails", text)

    def test_b4_cli_emits_query_note_for_hunter(self) -> None:
        ctx = _registry_context(
            _registry_step(
                ordinal=1,
                provider_id="hunter",
                capability="email_verification",
                provider_type="api_provider",
                api_base_url="https://api.hunter.io/v2",
                required_env_vars=("HUNTER_API_KEY",),
            ),
        )
        text = render_recipe(ctx, "cli").body.decode("utf-8")
        # No Authorization header — Hunter uses query param.
        self.assertNotIn("Authorization", text)
        # Note explains the query-param shape.
        self.assertIn("authenticates via query parameter", text)
        self.assertIn("HUNTER_API_KEY", text)
        # Default method (GET) means no -X flag.
        self.assertNotIn("-X POST", text)
        self.assertIn("https://api.hunter.io/v2/v2/email-verifier", text)

    # ---- B5: markdown footer + gap links point to planmyagents.com. -------
    def test_b5_markdown_uses_planmyagents_com_not_ai(self) -> None:
        out = render_recipe(_two_step_context(with_gap=True), "markdown")
        text = out.body.decode("utf-8")
        self.assertIn("https://planmyagents.com", text)
        self.assertNotIn("planmyagents.ai", text)

    # ---- B6: install-resolvability check refuses unresolvable npm pkgs. ---
    def test_b6_install_check_parses_npm_package(self) -> None:
        from planmyagents_api.planner.recipe_export.install_check import (
            _parse_npm_package,
        )
        self.assertEqual(
            _parse_npm_package("npx -y @modelcontextprotocol/server-memory"),
            "@modelcontextprotocol/server-memory",
        )
        self.assertEqual(_parse_npm_package("npx -y some-mcp"), "some-mcp")
        self.assertIsNone(_parse_npm_package("docker run my-mcp"))
        self.assertIsNone(_parse_npm_package(""))

    def test_b6_renderer_drops_unresolvable_mcp_when_flag_enabled(self) -> None:
        import os
        from unittest import mock

        ctx = RecipeContext(
            goal_id="g_b6",
            goal_text="MCP install-check smoke",
            steps=(
                RecipeStep(
                    ordinal=1,
                    capability="filesystem",
                    description="Mount filesystem",
                    recommendation=RecommendedProvider(
                        provider_id="fake-mcp",
                        display_name="Fake MCP",
                        provider_type="mcp_server",
                        install_command="npx -y @does-not-exist/totally-fake-mcp",
                        required_env_vars=(),
                    ),
                ),
            ),
        )

        with mock.patch.dict(
            os.environ, {"PLANMYAGENTS_CHECK_NPM_RESOLVABILITY": "true"}
        ):
            with mock.patch(
                "planmyagents_api.planner.recipe_export.claude_desktop_json"
                ".is_install_resolvable_via_npm",
                return_value=False,
            ):
                payload = json.loads(
                    render_recipe(ctx, "claude_desktop_json").body.decode("utf-8")
                )

        self.assertEqual(payload["mcpServers"], {})
        unexportable = payload["_planmyagents"]["unexportable_steps"]
        self.assertEqual(len(unexportable), 1)
        self.assertIn("install_unresolvable", unexportable[0]["reason"])


if __name__ == "__main__":
    unittest.main()
