"""Markdown recipe renderer — human-readable runbook.

Always succeeds, even if every step is a TODO. This is the
universal fallback every other renderer falls back to when an
unfamiliar shape comes through.
"""

from __future__ import annotations

from planmyagents_api.planner.recipe_export import (
    RecipeContext,
    RecipeStep,
    RenderedRecipe,
)


def render(context: RecipeContext) -> RenderedRecipe:
    lines: list[str] = []
    coverage = context.coverage
    lines.append(f"# Recipe for: {context.goal_text}")
    lines.append("")
    lines.append(
        f"_Planned by PlanMyAgents (goal_id `{context.goal_id}`, "
        f"{context.step_count} step{'s' if context.step_count != 1 else ''}, "
        f"{coverage.recommended_step_count} recommended, "
        f"{coverage.exportable_step_count} exportable, "
        f"{coverage.gap_count} gap{'s' if coverage.gap_count != 1 else ''}, "
        f"status `{coverage.status}`)._"
    )
    if context.planner_tier:
        lines.append(f"_Planner tier: `{context.planner_tier}`._")
    if context.cost_estimate_usd is not None:
        lines.append(
            f"_Estimated cost: ${context.cost_estimate_usd:.4f} USD per run._"
        )
    lines.append("")

    if context.notes:
        lines.append("## Notes")
        for note in context.notes:
            lines.append(f"- {note}")
        lines.append("")

    if not context.steps:
        lines.append("> The planner produced no sub-tasks for this goal — ")
        lines.append("> try a more specific phrasing or check `/discovery-gaps`.")
        return _emit(lines)

    lines.append("## Steps")
    lines.append("")
    for step in context.steps:
        lines.extend(_render_step(step))
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "Generated by [PlanMyAgents](https://planmyagents.com). Run the "
        "recipe in your own environment with your own credentials — "
        "PlanMyAgents does not execute on your behalf."
    )
    return _emit(lines)


def _render_step(step: RecipeStep) -> list[str]:
    lines: list[str] = []
    lines.append(f"### Step {step.ordinal} — {step.capability}")
    lines.append("")
    lines.append(step.description)
    lines.append("")
    if step.recommendation is None:
        lines.append("**No recommended provider yet.** Steps to take yourself:")
        lines.append("")
        lines.append(
            f"1. Search the [PlanMyAgents discovery index]"
            f"(https://planmyagents.com/search?capability={step.capability}) "
            f"for `{step.capability}` providers."
        )
        lines.append(
            "2. If nothing surfaces, file an Open MCP Opportunity at "
            "[/open-mcp-opportunities](https://planmyagents.com/open-mcp-opportunities) "
            "so we know to prioritise discovery for this capability."
        )
        return lines

    rec = step.recommendation
    lines.append(f"**Recommended provider:** `{rec.display_name or rec.provider_id}`")
    lines.append("")
    lines.append(f"- **Provider id:** `{rec.provider_id}`")
    lines.append(f"- **Type:** `{rec.provider_type}`")
    if rec.docs_url:
        lines.append(f"- **Docs:** [{rec.docs_url}]({rec.docs_url})")
    if rec.install_command:
        lines.append("- **Install:**")
        lines.append("")
        lines.append("  ```bash")
        lines.append(f"  {rec.install_command}")
        lines.append("  ```")
    if rec.api_base_url:
        lines.append(f"- **API base URL:** `{rec.api_base_url}`")
    if rec.required_env_vars:
        env_list = ", ".join(f"`{name}`" for name in rec.required_env_vars)
        lines.append(f"- **Required environment variables:** {env_list}")
    lines.append(
        f"- **Verification:** `{rec.verification_status}` · "
        f"**Benchmark:** `{rec.benchmark_status}`"
    )
    if step.alternates:
        alternate_names = ", ".join(
            f"`{alt.display_name or alt.provider_id}`" for alt in step.alternates
        )
        lines.append(f"- **Alternates:** {alternate_names}")
    if step.inputs:
        lines.append("")
        lines.append("**Inputs (from your goal):**")
        lines.append("")
        lines.append("```json")
        import json

        lines.append(json.dumps(step.inputs, indent=2, sort_keys=True))
        lines.append("```")
    return lines


def _emit(lines: list[str]) -> RenderedRecipe:
    body = ("\n".join(lines) + "\n").encode("utf-8")
    return RenderedRecipe(
        body=body, content_type="text/markdown; charset=utf-8", filename_suffix=".md"
    )
